src/Entity/Liste.php
<?php

namespace App\Entity;

use App\Repository\ListeRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=ListeRepository::class)
 */
class Liste
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $user;

    /**
     * @ORM\Column(type="integer")
     */
    private $user_id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $email;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getUser(): ?string
    {
        return $this->user;
    }

    public function setUser(string $user): self
    {
        $this->user = $user;

        return $this;
    }

    public function getUserId(): ?int
    {
        return $this->user_id;
    }

    public function setUserId(int $user_id): self
    {
        $this->user_id = $user_id;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }
}

src/Form/ListeType.php
<?php

namespace App\Form;

use App\Entity\Liste;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ListeType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('user')
            ->add('user_id')
            ->add('email')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Liste::class,
        ]);
    }
}

src/Controller/ListeController.php
<?php

namespace App\Controller;

use App\Entity\Liste;
use App\Form\ListeType;
use App\Repository\ListeRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/liste')]
class ListeController extends AbstractController
{
    #[Route('/', name: 'liste_index', methods: ['GET'])]
    public function index(ListeRepository $listeRepository): Response
    {
        return $this->render('liste/index.html.twig', [
            'listes' => $listeRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'liste_new', methods: ['GET','POST'])]
    public function new(Request $request): Response
    {
        $liste = new Liste();
        $form = $this->createForm(ListeType::class, $liste);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($liste);
            $entityManager->flush();

            return $this->redirectToRoute('liste_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('liste/new.html.twig', [
            'liste' => $liste,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'liste_show', methods: ['GET'])]
    public function show(Liste $liste): Response
    {
        return $this->render('liste/show.html.twig', [
            'liste' => $liste,
        ]);
    }

    #[Route('/{id}/edit', name: 'liste_edit', methods: ['GET','POST'])]
    public function edit(Request $request, Liste $liste): Response
    {
        $form = $this->createForm(ListeType::class, $liste);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('liste_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('liste/edit.html.twig', [
            'liste' => $liste,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'liste_delete', methods: ['POST'])]
    public function delete(Request $request, Liste $liste): Response
    {
        if ($this->isCsrfTokenValid('delete'.$liste->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($liste);
            $entityManager->flush();
        }

        return $this->redirectToRoute('liste_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/liste/_delete_form.html.twig
<form method="post" action="{{ path('liste_delete', {'id': liste.id}) }}" onsubmit="return confirm('Bist Du dir da ganz sicher?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ liste.id) }}">
    <button class="btn btn-danger">Löschen</button>
</form>

templates/liste/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn btn-light">{{ button_label|default('speichern') }}</button>
{{ form_end(form) }}

templates/liste/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Liste{% endblock %}

{% block body %}
    <h1>Edit Liste</h1>

    {{ include('liste/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('liste_index') }}">Zurück zur Liste</a>

    {{ include('liste/_delete_form.html.twig') }}
{% endblock %}

templates/liste/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Liste index{% endblock %}

{% block body %}
    <div class="container">


    <h1>Liste index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>User</th>
                <th>User_id</th>
                <th>Email</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for liste in listes %}
            <tr>
                <td>{{ liste.id }}</td>
                <td>{{ liste.user }}</td>
                <td>{{ liste.userId }}</td>
                <td>{{ liste.email }}</td>
                <td>
                    <a href="{{ path('liste_show', {'id': liste.id}) }}">Anzeigen</a>
                    <a href="{{ path('liste_edit', {'id': liste.id}) }}">Bearbeiten</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="5">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('liste_new') }}">Neuer Eintrag</a>
    </div>
{% endblock %}

templates/liste/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Liste{% endblock %}

{% block body %}
    <h1>Create new Liste</h1>

    {{ include('liste/_form.html.twig') }}

    <a href="{{ path('liste_index') }}">Zurück zur liste</a>
{% endblock %}

templates/liste/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Liste{% endblock %}

{% block body %}
    <h1>Liste</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ liste.id }}</td>
            </tr>
            <tr>
                <th>User</th>
                <td>{{ liste.user }}</td>
            </tr>
            <tr>
                <th>User_id</th>
                <td>{{ liste.userId }}</td>
            </tr>
            <tr>
                <th>Email</th>
                <td>{{ liste.email }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('liste_index') }}">Zurück</a>

    <a href="{{ path('liste_edit', {'id': liste.id}) }}">Bearbeiten</a>

    {{ include('liste/_delete_form.html.twig') }}
{% endblock %}